export const recentTrips = [
  {
    id: "TRIP001",
    user: "Aman Patel",
    driver: "Rakesh Kumar",
    amount: "₹220",
    status: "completed",
    date: "10:24 AM",
  },
  {
    id: "TRIP002",
    user: "Neha Sharma",
    driver: "Imran Khan",
    amount: "₹150",
    status: "cancelled",
    date: "9:55 AM",
  },
  {
    id: "TRIP003",
    user: "Ritu Singh",
    driver: "Vikas Rana",
    amount: "₹290",
    status: "completed",
    date: "9:12 AM",
  },
];

// Driver wise detailed trips 
export const driverTrips = [
  {
    id: "TRIP001",
    tripId: "TRIP001",
    driverId: "DR001",
    driverName: "Rakesh Kumar",
    userName: "Aman Patel",
    paymentStatus: "paid",
    pickup: "Baner, Pune",
    drop: "Kothrud, Pune",
    distanceKm: 8.5,
    durationMinutes: 24,
    amount: 220,
    paymentId: "PAY12345",
    status: "completed",
    date: "2025-11-20 10:24",
  },
  {
    id: "TRIP002",
    tripId: "TRIP002",
    driverId: "DR001",
    driverName: "Rakesh Kumar",
    userName: "Neha Sharma",
    paymentStatus: "cancelled",
    pickup: "Wakad, Pune",
    drop: "Hinjewadi, Pune",
    distanceKm: 3.1,
    durationMinutes: 10,
    amount: 90,
    paymentId: "PAY12346",
    status: "cancelled",
    date: "2025-11-20 09:10",
  },
  {
    id: "TRIP003",
    tripId: "TRIP003",
    driverId: "DR002",
    driverName: "Imran Khan",
    userName: "Ritu Singh",
    paymentStatus: "paid",
    pickup: "Viman Nagar, Pune",
    drop: "Kharadi, Pune",
    distanceKm: 6.2,
    durationMinutes: 18,
    amount: 180,
    paymentId: "PAY12347",
    status: "completed",
    date: "2025-11-20 08:45",
  },
];
